### ISSUE TITLE
Move this into Kemal core middlewares

### ISSUE THREAD

**Issue by sdogruyol** [werner/kemal-filters#1]
Hey @werner ,

First of all thanks for making this as a middleware. At first i thought that keeping this feature out of the core middlewares would be OK but recently a lot of people is asking for `before/after` filters without knowing this plugin.

That's why i want to include this under https://github.com/sdogruyol/kemal/tree/master/src/kemal/middleware .

Since this is opt-in and can be used like `add_filters` i think this is OK to be in there.

WDYT?

**Comment by sdogruyol** [comment]
Up

**Comment by werner** [comment]
Sorry for the late response, no problem, I'll be working in the PR ASAP.

Bests.
